################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
cc26xxware_2_21_03_15980/driverlib/adi.obj: ../cc26xxware_2_21_03_15980/driverlib/adi.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/adi.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/aon_batmon.obj: ../cc26xxware_2_21_03_15980/driverlib/aon_batmon.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/aon_batmon.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/aon_event.obj: ../cc26xxware_2_21_03_15980/driverlib/aon_event.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/aon_event.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/aon_ioc.obj: ../cc26xxware_2_21_03_15980/driverlib/aon_ioc.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/aon_ioc.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/aon_rtc.obj: ../cc26xxware_2_21_03_15980/driverlib/aon_rtc.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/aon_rtc.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/aon_wuc.obj: ../cc26xxware_2_21_03_15980/driverlib/aon_wuc.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/aon_wuc.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/aux_adc.obj: ../cc26xxware_2_21_03_15980/driverlib/aux_adc.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/aux_adc.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/aux_smph.obj: ../cc26xxware_2_21_03_15980/driverlib/aux_smph.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/aux_smph.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/aux_tdc.obj: ../cc26xxware_2_21_03_15980/driverlib/aux_tdc.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/aux_tdc.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/aux_timer.obj: ../cc26xxware_2_21_03_15980/driverlib/aux_timer.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/aux_timer.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/aux_wuc.obj: ../cc26xxware_2_21_03_15980/driverlib/aux_wuc.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/aux_wuc.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/ccfgread.obj: ../cc26xxware_2_21_03_15980/driverlib/ccfgread.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/ccfgread.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/chipinfo.obj: ../cc26xxware_2_21_03_15980/driverlib/chipinfo.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/chipinfo.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/cpu.obj: ../cc26xxware_2_21_03_15980/driverlib/cpu.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/cpu.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/crypto.obj: ../cc26xxware_2_21_03_15980/driverlib/crypto.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/crypto.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/ddi.obj: ../cc26xxware_2_21_03_15980/driverlib/ddi.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/ddi.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/debug.obj: ../cc26xxware_2_21_03_15980/driverlib/debug.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/debug.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/driverlib_release.obj: ../cc26xxware_2_21_03_15980/driverlib/driverlib_release.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/driverlib_release.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/event.obj: ../cc26xxware_2_21_03_15980/driverlib/event.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/event.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/flash.obj: ../cc26xxware_2_21_03_15980/driverlib/flash.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/flash.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/flashsafe.obj: ../cc26xxware_2_21_03_15980/driverlib/flashsafe.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/flashsafe.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/gpio.obj: ../cc26xxware_2_21_03_15980/driverlib/gpio.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/gpio.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/i2c.obj: ../cc26xxware_2_21_03_15980/driverlib/i2c.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/i2c.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/i2s.obj: ../cc26xxware_2_21_03_15980/driverlib/i2s.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/i2s.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/interrupt.obj: ../cc26xxware_2_21_03_15980/driverlib/interrupt.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/interrupt.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/ioc.obj: ../cc26xxware_2_21_03_15980/driverlib/ioc.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/ioc.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/osc.obj: ../cc26xxware_2_21_03_15980/driverlib/osc.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/osc.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/prcm.obj: ../cc26xxware_2_21_03_15980/driverlib/prcm.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/prcm.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/pwr_ctrl.obj: ../cc26xxware_2_21_03_15980/driverlib/pwr_ctrl.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/pwr_ctrl.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/rfc.obj: ../cc26xxware_2_21_03_15980/driverlib/rfc.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/rfc.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/rom_crypto.obj: ../cc26xxware_2_21_03_15980/driverlib/rom_crypto.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/rom_crypto.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/setup.obj: ../cc26xxware_2_21_03_15980/driverlib/setup.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/setup.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/smph.obj: ../cc26xxware_2_21_03_15980/driverlib/smph.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/smph.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/ssi.obj: ../cc26xxware_2_21_03_15980/driverlib/ssi.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/ssi.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/sys_ctrl.obj: ../cc26xxware_2_21_03_15980/driverlib/sys_ctrl.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/sys_ctrl.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/systick.obj: ../cc26xxware_2_21_03_15980/driverlib/systick.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/systick.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/timer.obj: ../cc26xxware_2_21_03_15980/driverlib/timer.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/timer.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/trng.obj: ../cc26xxware_2_21_03_15980/driverlib/trng.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/trng.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/uart.obj: ../cc26xxware_2_21_03_15980/driverlib/uart.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/uart.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/udma.obj: ../cc26xxware_2_21_03_15980/driverlib/udma.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/udma.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/vims.obj: ../cc26xxware_2_21_03_15980/driverlib/vims.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/vims.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cc26xxware_2_21_03_15980/driverlib/watchdog.obj: ../cc26xxware_2_21_03_15980/driverlib/watchdog.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/interfaces" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/sensors" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/overrides" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/pa_table" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/patches" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/radio_files/rfc_api" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/driverlib" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/inc" --include_path="D:/CCS Workspace/Contiki Workspace/simplebroadcast_improved_recharge/cc26xxware_2_21_03_15980/linker_files" -g --define=DEBUG --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="cc26xxware_2_21_03_15980/driverlib/watchdog.pp" --obj_directory="cc26xxware_2_21_03_15980/driverlib" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


